### ISSUE TITLE
Permission for chunk-test action

### ISSUE THREAD

**Issue by Joe7670** [VolmitSoftware/React#299]
Since I got no reply on the discord i'm just guessing it hasn't been done so yeah, need a permission node to give moderators for specifically this action.

**Comment by cyberpwnn** [comment]
Sorry, diddnt see it and i guess no one added an issue for it for you. Thanks for the issue.

**Comment by Joe7670** [comment]
Hey.. bump. Been waiting for this for quite a while. I hope it's not anything tricky

**Comment by lucas2107** [comment]
@Joe7670 cyberpwn is working on criticals bugs before adding new options ^^

**Comment by cyberpwnn** [comment]
All action permissions updated in 6.541
```yml
react.act:
  description: Gives access to use actions (all subtypes included)
  default: op
  children:
    react.act.gc: true
    react.act.chunk-test: true
    react.act.timings-report: true
    react.act.file-size: true
    react.act.dump: true
    react.act.cpu-score: true
    react.act.cull-entities: true
    react.act.fix-lighting: true
    react.act.lock-fluid: true
    react.act.lock-hopper: true
    react.act.lock-redstone: true
    react.act.purge-chunks: true
    react.act.purge-entities: true
    react.act.unlock-fluid: true
    react.act.unlock-hopper: true
    react.act.unlock-redstone: true
```
