### ISSUE TITLE
Feature request: config.yml modification

### ISSUE THREAD

**Issue by SlimeDog** [VolmitSoftware/React#316]
Spigot 1.12.2
React 6.3.5

The console subscriptions work fine, except for one thing:
- If I comment out one of the listen-channels (say "verbose"), the comment is deleted on restart.

Please modify the config to support:
- Individual true/false for the listen-channels:
- Comments (in addition to the ones React provides itself)

Suggested config example:
```
  console:
    # Uses the listen-channels to print to the console.
    listen-channels-enabled: true
    listen-channels:
      rai: true
      spikes: true
      verbose: false
      action: true
      gc: true
```
Missing listen-channels should be evaluated as false, of course.
