### ISSUE TITLE
Entity Stacker: Add a blacklist for spawn reason and worlds

### ISSUE THREAD

**Issue by FabioZumbi12** [VolmitSoftware/React#331]
Hi. Can i suggest some more options to entity-stacking like a list of spawn reason to do not stack?
I am still using the plugin StackMob because a lot of options, but this option is the most important, and will be the reason to do not use the react stacker.

And blacklist to do not stack in certain worlds too if possible.

**Comment by cyberpwnn** [comment]
React mob stacking was not designed to offer features to improve mob stacking, it was designed to make servers faster, faster than even normal mob stacking plugins. So its quite different in that way which is why there arent specific features to sort out conditions like that (its faster that way)

I have added the option to disable stacking on a per world basis and spawn reasons.

### Disable Stacking in a world
In `plugins/React/worlds/YOUR_WORLD.yml`
```yml
allow:
  tile-throttling: true
  relighting: true
  entity-throttling: true
  fast-leaf-decay: true
  actions: true
  rai: true
  stacking: true # you can disable stacking here
entities:
  assume-no-side-effects:
  - ARMOR_STAND
```

### Modify Spawn Reason Filters
You can remove reasons from the list in the config.yml if you dont want react to attempt to stack them
```yml
stack-reasons:
    - natural
    - jockey
    - chunk_gen
    - spawner
    - egg
    - spawner_egg
    - lightning
    - build_snowman
    - build_irongolem
    - build_wither
    - village_defense
    - village_invasion
    - breeding
    - slime_split
    - reinforcements
    - nether_portal
    - dispense_egg
    - infection
    - cured
    - ocelot_baby
    - silverfish_block
    - mount
    - trap
    - ender_pearl
    - shoulder_entity
    - custom
    - default
```

I have also added options to disable on-spawn stacking AND on-interval stacking
```yml
    # Try to stack entities around a newly spawned entity.
    stack-on-spawn: true

    # Try to stack entities in different locations on an interval.
    stack-on-interval: true
```

Implemented in 6.5.1
