### ISSUE TITLE
Fast leaf decay incompatible  with coreprotect

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/React#349]
This feature blocks the logging to coreprotect. Normally when a tree decays naturally coreprotect logs it as "#decay removed leaves". When using react it breaks this functionality. Is it possible to make this feature compatible with coreprotect? Love the plugin keep up the great work 🙂

**Comment by cyberpwnn** [comment]
Yup I'll either manually add the logs to core protect or use some trickery to get it to log it

**Comment by cyberpwnn** [comment]
I am attempting to re-fire the leaves decay event. With coreprotect you need to capture leaf decay events. I have modified the event calling so that coreprotect has a chance to get the previous block type. 

Added in 6.541.

Re-open this if 6.541 does not fix the issue.

**Comment by LogGits** [comment]
Unfortunately it doesn't seem to log on the latest build. If necessary:
```yaml
  fast-leaf-decay:

    # Trigger fast leaf decay when leaves decay normally
    trigger-on-decay: true

    # Use fast block destruction for fast leaf decay. Turn this on if you dont like
    # snow floating above leaves, though you loose most of the performance benefits
    # of fast decay.
    fast-destroy: true

    # Saturate the destruction queue as fast as possible, ignoring tick limits.
    instantaneous: false

    # The period of time (in ticks) which a leaf block that is marked for decay
    # will actually decay. If 10 blocks are set to be destroyed, they will be
    # destroyed randomly within 5 ticks (by default)
    decay-period: 5

    # The maximum milliseconds react is allowed to use to fast-leaf decay
    max-ms: 0.8
    enabled: true
```
Also what triggers the fast leaf decay? Sometimes its fast and other times it decays slowly like regular minecraft.
