### ISSUE TITLE
React entity stacking issues and suggestions

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/React#433]
React entity stacking stacks mobs regardless of my settings:

This stacks mobs regardless of my settings:
```yaml
    stack-reasons:
    - spawner
    - slime_split
    - dispense_egg
```
All mobs stack regardless. E.g. sheep (even stacking some different coloured ones together), pigs, cows, chickens (**Version: 6.568**).

Im using paperspigot build 1499.
```yaml
  entity-stacker:
    options:

      # Format for nametags
      # %size% = Number of entities in stack
      # %type% = Entity type
      # i.e. Pig
      # %hp% = Health
      # Color codes and formatting supported.
      nametag-format: '&c%size%x &b%type% &a%hp%'

      # Increase sheep wool drops depending on stack size
      sheep-wool-drops: true

      # Show a nametag of the stacked entity
      show-nametag: true

      # Show particles on stacked entities. More particles = bigger stack. This is if
      # you don't want to directly show players the stack size.
      show-particles: true

    # Try to stack entities in different locations on an interval.
    stack-on-interval: true

    # Speed up interval stacking by queueing each entity to stack as often as
    # possible in a 1 second time window.
    fast-intervals: false

    # The radius (in blocks) to search for entities to stack together.
    search-radius: 4
    enabled: true

    # Scale all damage causes except for player x entity damage with the stack
    # size. This means a stacked pig would have the same effective health by
    # scaling damage to that pig. Excludes player damage.
    non-player-damage-normalization: true

    # The maximum size an entity stack can have
    max-stack-size: 20

    # The minimum number of entities required in a search radius to actually create
    # a stack. Setting this lower will create frequent small-stacks, higher will
    # make larger stacks less often.
    minimum-group-size: 5
    stack-reasons:
    - spawner
    - slime_split
    - dispense_egg

    # The maximum health a stacked entity can have. (make sure this is below
    # spigots limits if you changed them)
    max-health: 1600

    # Try to stack entities around a newly spawned entity.
    stack-on-spawn: false

    # Cache stack data through reboots, unloads and reloads.
    persist-stacks: true
```

*Suggestions for stacking*
Option to have it ignore stacking these:
- Skeleton types
- Leashed Mobs
- Villager Profession/career (including babies)
- Parrot colours
- Llama colours
- Horse colours
- Slime size
- Fish type
